apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openproject
namePrefix: openproject-
components:
  - ../../base/gateway
  - ../../base/gateway-zib-only
configMapGenerator:
  - name: gateway-config
    literals:
      - hostname=project.episerve.zib.de
      - secretName=openproject-tls
      - serviceName=openproject
      - servicePort=8080
      - listenerName=openproject-listeners
      - routeName=openproject-route
