apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
namePrefix: metabase-
resources:
  - ../base/gateway
  - trafficpolicy.yaml
replacements:
  - source:
      kind: ConfigMap
      name: metabase-gateway-config
      fieldPath: data.hostname
    targets:
      - select:
          kind: ListenerSet
          name: metabase-listeners
        fieldPaths:
          - spec.listeners.0.hostname
      - select:
          kind: ListenerSet
          name: metabase-acme-listeners
        fieldPaths:
          - spec.listeners.0.hostname
      - select:
          kind: HTTPRoute
          name: metabase-route
        fieldPaths:
          - spec.hostnames.0
      - select:
          kind: Certificate
          name: metabase-tls
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: ConfigMap
      name: metabase-gateway-config
      fieldPath: data.secretName
    targets:
      - select:
          kind: ListenerSet
          name: metabase-listeners
        fieldPaths:
          - spec.listeners.0.tls.certificateRefs.0.name
      - select:
          kind: Certificate
          name: metabase-tls
        fieldPaths:
          - spec.secretName
      - select:
          kind: ReferenceGrant
          name: metabase-tls-grant
        fieldPaths:
          - spec.to.0.name
  - source:
      kind: ConfigMap
      name: metabase-gateway-config
      fieldPath: data.serviceName
    targets:
      - select:
          kind: HTTPRoute
          name: metabase-route
        fieldPaths:
          - spec.rules.0.backendRefs.0.name
  - source:
      kind: ConfigMap
      name: metabase-gateway-config
      fieldPath: data.servicePort
    targets:
      - select:
          kind: HTTPRoute
          name: metabase-route
        fieldPaths:
          - spec.rules.0.backendRefs.0.port
  - source:
      kind: ConfigMap
      name: metabase-gateway-config
      fieldPath: data.listenerName
    targets:
      - select:
          kind: HTTPRoute
          name: metabase-route
        fieldPaths:
          - spec.parentRefs.0.name
configMapGenerator:
  - name: metabase-gateway-config
    literals:
      - hostname=metabase.episerve.zib.de
      - secretName=metabase-tls
      - serviceName=metabase
      - servicePort=3000
      - listenerName=metabase-listeners
      