apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ckan
namePrefix: ckan-
resources:
  - ../base/gateway
  - trafficpolicy.yaml
replacements:
  - source:
      kind: ConfigMap
      name: ckan-gateway-config
      fieldPath: data.hostname
    targets:
      - select:
          kind: ListenerSet
          name: ckan-listeners
        fieldPaths:
          - spec.listeners.0.hostname
      - select:
          kind: ListenerSet
          name: ckan-acme-listeners
        fieldPaths:
          - spec.listeners.0.hostname
      - select:
          kind: HTTPRoute
          name: ckan-route
        fieldPaths:
          - spec.hostnames.0
      - select:
          kind: Certificate
          name: ckan-tls
        fieldPaths:
          - spec.dnsNames.0
  - source:
      kind: ConfigMap
      name: ckan-gateway-config
      fieldPath: data.secretName
    targets:
      - select:
          kind: ListenerSet
          name: ckan-listeners
        fieldPaths:
          - spec.listeners.0.tls.certificateRefs.0.name
      - select:
          kind: Certificate
          name: ckan-tls
        fieldPaths:
          - spec.secretName
      - select:
          kind: ReferenceGrant
          name: ckan-tls-grant
        fieldPaths:
          - spec.to.0.name
  - source:
      kind: ConfigMap
      name: ckan-gateway-config
      fieldPath: data.serviceName
    targets:
      - select:
          kind: HTTPRoute
          name: ckan-route
        fieldPaths:
          - spec.rules.0.backendRefs.0.name
  - source:
      kind: ConfigMap
      name: ckan-gateway-config
      fieldPath: data.servicePort
    targets:
      - select:
          kind: HTTPRoute
          name: ckan-route
        fieldPaths:
          - spec.rules.0.backendRefs.0.port
  - source:
      kind: ConfigMap
      name: ckan-gateway-config
      fieldPath: data.listenerName
    targets:
      - select:
          kind: HTTPRoute
          name: ckan-route
        fieldPaths:
          - spec.parentRefs.0.name
configMapGenerator:
  - name: ckan-gateway-config
    literals:
      - hostname=ckan.episerve.zib.de
      - secretName=ckan-tls
      - serviceName=ckan
      - servicePort=80
      - listenerName=ckan-listeners
      