apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secret.yaml
helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: "18.6.7"
    releaseName: metabase-postgresql
    namespace: default
    valuesInline:
      auth:
        username: metabase
        database: metabase
        existingSecret: metabase-db-credentials
        secretKeys:
          userPasswordKey: password
          adminPasswordKey: postgres-password
      primary:
        persistence:
          enabled: true
          storageClass: csi-rbd-sc
          size: 5Gi
  - name: metabase
    repo: https://pmint93.github.io/helm-charts
    version: "2.27.3"
    releaseName: metabase
    namespace: default
    valuesInline:
      database:
        type: postgres
        host: metabase-postgresql
        port: 5432
        dbname: metabase
        existingSecret: metabase-db-credentials
        existingSecretUsernameKey: username
        existingSecretPasswordKey: password
