apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
namePrefix: prefect-
components:
  - ../base/gateway
configMapGenerator:
  - name: gateway-config
    literals:
      - hostname=prefect.episerve.zib.de
      - secretName=prefect-tls
      - serviceName=prefect-server
      - servicePort=4200
      - listenerName=prefect-listeners
      - routeName=prefect-route
