apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-tls
spec:
  secretName: GATEWAY_SECRET_NAME
  dnsNames:
    - GATEWAY_HOSTNAME
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
