apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: ListenerSet
      name: GATEWAY_LISTENER_NAME
      sectionName: https
  hostnames:
    - GATEWAY_HOSTNAME
  rules:
    - backendRefs:
        - name: GATEWAY_SERVICE_NAME
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: /
            