apiVersion: gateway.kgateway.dev/v1alpha1
kind: TrafficPolicy
metadata:
  name: zib-only
spec:
  acl:
    defaultAction: deny
    rules:
      - action: allow
        cidrs:
          - 130.73.0.0/16
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: GATEWAY_ROUTE_NAME
