apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
namePrefix: argocd-
components:
  - ../base/gateway
configMapGenerator:
  - name: gateway-config
    literals:
      - hostname=argocd.episerve.zib.de
      - secretName=argocd-tls
      - serviceName=argocd-server
      - servicePort=80
      - listenerName=argocd-listeners
      - routeName=argocd-route
