apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - listenerset.yaml
  - listenerset-acme.yaml
  - httproute.yaml
  - certificate.yaml
  - referencegrant.yaml
  

