apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: argocd-acme-listeners
  namespace: argocd
spec:
  parentRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: shared-public-gateway
    namespace: kgateway-system
  listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      hostname: argo.medicalbioinformatics.de
      name: http
      port: 80
      protocol: HTTP
