apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
namePrefix: doip-server-
components:
  - ../../base/gateway
  - ../../base/gateway-zib-only
configMapGenerator:
  - name: gateway-config
    literals:
      - hostname=doip.episerve.zib.de
      - secretName=doip-server-tls
      - serviceName=doip-server
      - servicePort=80
      - listenerName=doip-server-listeners
      - routeName=doip-server-route
