apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ckan
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/The-EPISERVE-Consortium/episerve-k8s
    targetRevision: HEAD
    path: apps/ckan
  destination:
    server: https://kubernetes.default.svc
    namespace: ckan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
