---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-s3-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBWjWvkJkfyyK9QHc0K1Oy6hq+quXHzH5FmH0dArTz9oI6ikZdBzpLvbwYeqIMeChTiTpj1U/6R/KjC4NDR8IrKQ5H4bpgEsg644s1dSfE05CuoGG9BU61Xra8b3yFF08pmroA7Wq+Xa4jXTfjWRXhXGbX/NIWSVlX8M4TjcWv3gNwFcHdCW//W8L8UhQ4pnaJm9q2hZQhb0d4XNnyuD1IfkzD752MhEjF+h9jLK5INj4fInBm5sgqesHy3IQRO28ET5xUca9DChzlFBwdVu0CuFYCZT/xjvbOSAdMPfHc7NaKiLGCtqez0C0M55a+lA6j8NeXJat2zepXNeRhadl02MMmELP98xogm++a4bckVPO5/gEBFfU7lCEePOJmYGAOrs3aKe2akQibbymjz/w7hd7LE1DVH4XenZbZmvVd4EiyBj4ItBWPsW+hec5pbv6TcHEiUgTeSZmTv/PEDCPVs+5cKtl2H8vAwX61tfXyvzXPPOqb5VgkvUpL1ehzvtzlWfMsurqlpeYkWx4gRhfSSx1JF2kElBTXfODyE3JqjT8NNm1Nv+I0YzsFsxTWvkr0R9SJW+wG2uICBD+cG+SFdBLYcP7OhcEC3X+/2wmYrCDiY0WuSyIgdFVwGGgVuAqB4tFakGToDnmTf/n6b3xudwEGxNiFHSk1bH1cFpZCMFSQzxtw+ewruJTgYBe68eUYGndvIOS5eY8ksaqtFgk9kY0r9EgSRcyB2g8FNINLCh7cp5N57lO2YBURweN3Vpi1BW3kv/7Rf28WVX72yfdcmFMpNykoruFbNMUKGGkRDhffBD5dXeicUUXfWHLzJAUaF/kC0ApyUQ/fvjK6Rh9U=
  template:
    metadata:
      name: velero-s3-credentials
      namespace: velero
