---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: doip-link-secret
  namespace: ckan
spec:
  encryptedData:
    doip-link-secret: AgA6BwKladxx8HFwFkS6O2y5x0KLUzLqsCxD8vLcel+GyDd7O74AmO6Hl7lMbVBZcwv/bHk4U47s08BxhdFCles99m+dsp7UelgrvI6YO55roTWHssL+2dZbbQRDF0kk5mvMI2EwgczWPY57jV88fs0vJxmEZGUtWqjf+iQ6DR2gZuro2QlNlfaG+p0cHTPvlErPcwfcd7TEfEdx5/B3SWOxFOhQEll7j67t43FaSuA57MdXC9ey8svRXV+lX0+20YWts/QavuzH3tUoDr4en7J3eCAZiotPRcwT5xC6gH/8JN2YFY3Hkiq+azWAtmMhV5k23PfPgy+V/hdAJ66n0oxqNuX9yrTuTvVhTBtK5iErIBrbyMS+VR2FtvpoLb8B1iesZAdimhYB0mkzgatHu+WEs5smQHg28zU2mk2kEG+6G7OT/DgaGgF15W6HktNAgXdIj5S04hwEqL3ryctuuCwIkenKf6EirkYu3ukR6tQGZ+twi5vGnXXeuQ02gFPuijRwRRuHxtnKY1TDE04CjoGHgv/6k0HUVToJle/YSIqbK/q1xY32aMlBGeaGmYsbOAFdB29MgeXTgGYJv3qU+SUEUQZz4EZJrYBh2P6iWNDMxbmujdq0qaCkaBfujhIypIZ2wvTOXfsxEsI5MCux/PKoiiJCJPUd3EIZ718EoeDezwPitKjjTlfhnDwG2DxqPmDeLtx5Z3Umn4zT9DgQUP3MMbXT9Gqni7PQlMvGY1Ol9YOtqcyzpLqn6CEdiLO94BMcb56Yr6X1Q9fgIXw4Uafb
  template:
    metadata:
      name: doip-link-secret
      namespace: ckan
