apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan
spec:
  template:
    spec:
      initContainers:
        - name: install-ckan-plugins
          image: keitaro/ckan:2.11.4
          command:
            - pip
            - install
            - --user
            - --quiet
            - git+https://github.com/DataShades/ckanext-parquet.git
            - git+https://github.com/The-EPISERVE-Consortium/ckanext-episerve-theme.git
          env:
            - name: HOME
              value: /app
          volumeMounts:
            - name: ckan-user-local
              mountPath: /app/.local
      containers:
        - name: ckan
          env:
            - name: CKAN__PLUGINS
              value: "envvars episerve_theme activity image_view text_view datatables_view datastore xloader parquet_view"
            - name: CKAN___CKAN__PLUGINS
              value: "envvars episerve_theme activity image_view text_view datatables_view datastore xloader parquet_view"
          volumeMounts:
            - name: ckan-user-local
              mountPath: /app/.local
      volumes:
        - name: ckan-user-local
          emptyDir: {}
