---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb-credentials
  namespace: default
spec:
  encryptedData:
    mariadb-password: AgABMVZCqiKOIZbFR+14eiXV5+ktV2SRfqeCM5lzyJE58w/7uvj9+zBhx9+n0axVpjwRrdBvzEUmN+uxHZTJuv6xAioHdZaK2XFToApvFyJeRCk+DnXnHPUu/zk22FggKppqsqYtPl7i5Xnun8YRASZkLo1wQglhmioaig2QifbsROgl/m04WoVZUbRVbz+83h6sa1IcBUsajMBsxVefqbzVuSz1R+1mU5iG8ImnWJCo5tcw7GVLhihlnx2MfS1i6gMubV88wuVeyyFLqc2Q4QJm7FpWBBuR0FJwNyhY7x0lUEtmj9/51tvhKJOaUNZanFDI3wgVZt0Ve3aqH7I3eUZ66x6BEh1/rtzFF6yFmoECGOdyPlOSXsvj2f+2TMeQ4/n+sLMlpe0+GizTlaIaUlFmaWJ+xIIwK06GBOjnZR3fNhDNX/dvJd+xKOVxxS3COt+37INholenSkG/zUNy49trNoGUWSM6axVInP1VWG390gm8V20UqG4MyDoWpm6oTt6qGI+JG1OLKFYHuyVnbJcqJxd0+kKQlm+Z6KXW7Xel9a5MD+VHHc3h7ZKJxYzcXltHeMLDMivG3TJKF65ds+prNR825fjSFre9GEB1TRwPgqddKJG4tyvxbEifdieipgF3d25FXOuLCnVZLlN9ptHOD28tbvgDvKeO9z2xLZy9e7D9asfAQ2SufTIv//PumE0XxeZcqg7HCUCwwnQpK7OccSYaVxUAFUw+XRv/nGrNnA==
    mariadb-root-password: AgBxUDr7ZSl9mSE5CH3T/fR/FmlmF+xrPft9WwMS3ZA/k/cneBzHBbgPIt27rPCoUpAQpJ8dgvlcxxyir6GtDNroJjjiY1qLRedtrR5MaetXPhGUba5coI+zA9sP6xnodsQFHe5NvvLo7ul5/qfjC9FcL6/GEQYB/wj/RA9Zs+8xvfIpxdodfJxwidgYkDWYGHJdKE9RCcGz5ybM90MXf2NhJG+6XDX4QChsNF/d4B1z9xT2RyFIcVCCQM6QL6j9a8JqdmG5bN2ZB5eSZWgRRrlR9S/nPoI+b2ADuxOJq4PjuTP0ltuAZCCm9J8hJS/dIVMsppF0VJYfA6fjJptHi/IBEFbWKoKxlqFrLaLKoaM330zXj1Y0N6ObjRRlPb9gu/1VNNUBQm9l5tPjCDAxIrR2q6WAex9b3iLIfLlaLuy5m4xIYPSpe8Geaav5LLK5ZOmU6y5HCFUQncrtqDpiTcgBOtEfJJ6t6ztsJwmCf/lpFgKvGHtIhiVx3bEXzgFvC4HhMIF7H7NATeukgfEXdIMLB+83UT45xzKOts8/3Xa10S7CFwAZoPAdCNA2cHMvDbGMioZ5xUQK3FrIxm/fQThQTzckfm+9/morkufM62jV9M1fcEd9ITX7gkKN6uHrVmZPY9h5s+j7zxx4aabjqDUDewnG/PrphUxkOoNE4W1+TUGsoBakq5yKSBRLvjpPPlE6rgGdnW55icWFTmrrMWRlVq4iQQMcj0Xy+pnJ2Ujdnw==
  template:
    metadata:
      name: mariadb-credentials
      namespace: default
