apiVersion: ENC[AES256_GCM,data:Lmo=,iv:E4A1dXVfWomcq27C/HazNW++j19QrM8be0kE88lN+j4=,tag:lzkn3MfsMPNCwc3IY9lhsA==,type:str]
kind: ENC[AES256_GCM,data:6TjXFygm,iv:vDyXsFBfo6eBzM4cD1ur6i75MrM2OIV7p5MLB2qBPq4=,tag:BRKftg3/55lEJPfP6dfwkg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JGAJR9Mj9vGFzaOiA2F+0ZKHjA==,iv:zRDEJwPwGH7ZJeEgEoZanih0Aqat8212kNmB6MkyjOY=,tag:OF+RcYc+9W2BzC+37a5SaQ==,type:str]
    namespace: ENC[AES256_GCM,data:L3PcbsMWzg==,iv:UZw9G3oBYJa5qZZSMUM5Pv9McPN1EadDDI0zhMAbeZo=,tag:/TLgZmXyFcaGePp0rsTbcQ==,type:str]
type: ENC[AES256_GCM,data:wOQuRwpj,iv:RrVoy0UYyAkLSVEMDPOuuD++eBhxHVkyb817gLyA8WM=,tag:akSPZRE4atvvPmYI2huP1A==,type:str]
stringData:
    root-password: ENC[AES256_GCM,data:jGGO3dQsywzXzxWzHg0Dm4Bk3KDDO1ZwyT7i30QIMYE=,iv:/idBKce5ax6ZAWNG0u9Ms9S5KFytwBioN8aGr+YpwTA=,tag:4uy73x3ETtfRauAjKXkCGQ==,type:str]
    password: ENC[AES256_GCM,data:AaIVp9uyTZQX5uCplG8wXORkq19GBDJYLFAn4P1/zbE=,iv:OttVfHG6YLtTsqYvkvHwvJjUVmJIAlr1m3nEazfkdWk=,tag:Aj+TkRraBXm/YxZUSW8QCA==,type:str]
sops:
    lastmodified: "2026-05-20T10:46:54Z"
    mac: ENC[AES256_GCM,data:MiZ+ErVcbiMIGqQ508n6a8U3WZ06v/EPP5fJgtamsljV3fC7/a0eSbgkg5fbVlFjrDpQUY5kwkgWzypy1LLtSCEtpbAqpBNmVpxzC9nFBBWc+BmEMZ1U/LuVOyyZp6BZgpiMNjVtFQkcYrIe6jGuyNa+ObCxTK07eh4ud7rRe7I=,iv:PeW0K13mnFeXPXXbSipxkGGAnVPIx9j+jXqBoQFyChY=,tag:CY5cmH9mbpm8o8IqnyOGrA==,type:str]
    pgp:
        - created_at: "2026-05-20T10:46:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA6LtCB99mFtFAQ/8CksRxkFFcxRfvfqd82uzlqvmetn0ruhrrXx2eEqYUqEA
            btevWvDbrWN5YY/KN/SPAvUXqp+7wgLtwa+4iuBgr8ckoQ81/tvyMZPzlkzLFMTw
            xGXy1ePeDX2EtFa19kJvl9cpPGd/NWXZtRdUzdQZsulqsrH0xoylqAyHirlbD3ye
            o66ZfX/uTztLQt0mMZrVnxQw1SKCTGQSiV0YVevJjZTiKkherk+HfDbtiap1X6mt
            aao+3YNm0FkcNi3CzZ1BlJryPVfnIpGJFXntxAz0zH3QQ40x7WEqrclwGZ4D8No0
            MUfrEQLPaxZHlK4htotql0nsFIFvv6Nt6fbUTZbKq7bELyedhGuLUr7zaR2D3d3Z
            sxagOBaDQeIlu19VunwvPRKlgZ03QHP1UTScrRUG+C9+zvcwn7+ldsM24HhnrBDM
            g1Rcm3+saI3gzN6AMkfLwsVAeeJSrdXLHqkRLAFkHYcsLCn7BCsHIDtl9yYwCB5v
            qdfyC9rl+n7Ay2hM7TK7taf+LSzHNUzFUgyPE0yN/PYY1bPWoF9a/3pilgQH6Uqg
            1w4fpewNUwMI1f436mztky5vI52on5N+sKxO0y6awMWFJme3XCkSbwZL0s2KsWPW
            FLYgoB1aahh9ufr1O28J7eBO0BQqVqc0ZWJBD34GvCFaoVDklPm/7wNfDVeIIBzS
            XgE5u7vqqvrflms+sZLrDSJ/HiCtnhegqFYfdarGUjKWpfwvomXNnA4KHM7htww9
            Mn+dwCbn0yM9JcGToHQenN6au1hErrfkruYcxewRb+H19AWCjLh75GK1noT8R6A=
            =EjEM
            -----END PGP MESSAGE-----
          fp: 96E23B72D97E26ED
    unencrypted_suffix: _unencrypted
    version: 3.13.1
