auth:
  existingSecret: mariadb-credentials
  database: test
  username: mariadb
primary:
  persistence:
    enabled: true
    storageClass: csi-rbd-sc
    size: 10Gi
  service:
    type: LoadBalancer
    