---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apify-credentials
  namespace: default
spec:
  encryptedData:
    apify-api-token: AgAVgERAmA6CgwkKzXTdKWGbzs75iy9QX+2L2/4QHpov6cCK6ejxt0PPb7eQDURsINosdCYpDwkfnk0Qs526CJYR4O9G9BcSP4LVH4SW8OiITYA3N1Iaz5UgImpaIV7Ti4J/AvdQHb3shtKHdBDCw3DQGHviAkrqwIvAag86z/XUinPy0F/OmMTHiIGKUmlqJmkJA7d0K7zznF2kc/ShrFDk9gjYcOO+p9LSRJFGZAMTc7O7fy/Tj0Z1d4A3BBajdWMBq8MH8weMjqZ5oP+mEfDTmlSl6PC5RHPZvTNa+uLGvSO/OsmEfXnVGsH2XpDGgQh2ijwADCfHtqeMEwnkkdBYwc18Sku2qets96B3ZMDfO7SsT0as+EYeWrmKOIG6Cm3e86AIncKD7w7TcdwvGm+sJWR6P1Q0uf6O+cISt0fyLB/rrMEO5xpoKIv2iTxptr0w1LeLmr7nfVCTIuBmHRXvI6/f70ruDNY0MeIXLYcGd18TxHgxC/P+o5AtbsJl+fDtDlaAfoKgYIXmVHOGtmjSzcGz+Xtfrhy/EvE71d/gBa9MTzqxCprdWnw6xnYwM14U2oMLDPMEPNGV4wLycdYPq11JaJbUTD6+fUVwLsgsRQTnYt1ZZvj54XCyxuWfDqHaIXuUqGtmaW2jJHiBoyfO12ASdj9sobdiLk+YMtBlDu3hAV7C0DQClgkdhkdIOPmJFoku2XPbR8yaUn+ENdQoohSzQjUVZ9mLKn0F0xqqm1sbJ+TlHfirqUuOadxL
  template:
    metadata:
      name: apify-credentials
      namespace: default
