---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: author-hash-credentials
  namespace: default
spec:
  encryptedData:
    author-hash-salt: AgAxbxy1ymaNwye3GPHYYXZ3msZ1ysaYSxyezwYRwoygh8Qvlm7Nxiw1MiYQiMkpg1yuJ/u4XzQbNMTifNxpXZHJwgooQzNsUgJ2ysT8IwMJmPg2l/+NHsdGzksnMzi2IM5xyfV8VANQAYsHwMzDV48/4PaORTqQKuv55LG/zK1U/KsquZCPLXJsjNr3I3m2JIizn6k0xAiyPWH3zyO1CdxIsrwRm1EV4ONsBffW13koYqHc0D+e9Qjikd15eLbnaAcmD0msBeMkoIsvhnEv4aUqjcuJPA5y4YN2bnuOM59vmYUZPdrAGxYevFpdS3LhjaCdmcHpPMU0l+wsDSDAWu0OmZYY0sT1WBVXdsxuab4v23HkzaU3Ojc1YQ6Bbnb6x76uNI+mDwss0gc0HliZwBKjn6py9p+Y5EOb1U7egSTMuAGFdKZErLOJhQzRgarH7nwYYiGCMoVDRYoMEWPzu+bC0hrQ2W3BAg/wwZq6GWVYfJdc81fmktwGigPTaE0YCZuAvbCb33a6A846Rp0Wm/RvJTS/+6E0oaJ41y0s0vpv1dDbLQ51waSa8bdJCDrfP0yxmoHm9uVYiw8JKdkEBKmUKrSy5Ck2/5YflH8xyJSVZZPW7k8tfqmfsB7UE5I3XgU5f14OD/qNx0NGbwNY2geVUyA8PO9N3XqKeymLNBP5Z0USK8DRfh9vs3m+XK6A3VKi1mNxSEnQVuvVoVhwPP8JFuyDDEa0CHlbsRyoHMRXFbmtf5oxagnpUXxvgXchqa8ZqWd62BTzK8Xv4W+H1NaG
  template:
    metadata:
      name: author-hash-credentials
      namespace: default
