---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: blackboard-credentials
  namespace: default
spec:
  encryptedData:
    blackboard-password: AgCO421sBSDf0+JBVaa9y+yZPw5RO7bFMHFXUlTLfq2yc43BMbHpYqTFKoO9S54xrhviJUufcxeNyTlCQZdnCgvB3mUwwUZE1NEG7qcsOsUse4nxkURQRatKgvTDC834qBaEoPwh7V6xA3jjaYlY+iAraT3uDOEkP9tw0q0t+JLdqZlBcY2F01748BquCMjF2xASqxW2pZ6vBoDlRKPciWEStZKepu4+FI7O31Wf7TRfw1CfaK0K8RmUgWwrulax83MWcZpoxbciIgSwWoOUq/bD8CVV2+NPN7M76ZQHJhVgGFflVrKfdR7uJMMmsA+ijriCTc/1Y1sngi+qO3PVeZpMX9WpajCYiKB6ZzDH54dbeWvgJD0asts5NHe21IlYhuj5bm1oL17jueq/Az2dzYn1DUpjd0sZwAzd3LvzEaAm7GO5ConPIOsy8s5n9rTNZ+fFsvK/U95B3rjTZ4fvpm7oiQmKXs4pfLLQHV7tayuY/nKFndzASZXrYR0c3FW/rr5Mdds4F6/jTtUlYafnrnaE4sdvwbRx8fRTK0hB2fNDlEgAf9sPheiSswXFQoA9yOQnVcTKCgH4kyWEA5Jwc88cnWkvYH455BBYJW9b09wlytm6fjAoRqgT2OryCloTTKSR8ZkC4krBFQom+aaubVpAp1zEdDnaRnYpOXl0hgWDx2+/f2DhSQL88E33RGtZM9TFbjcQwmRQzf4qlJd8FeU1f3dmYtRioySIOejrMNHsSQ==
  template:
    metadata:
      name: blackboard-credentials
      namespace: default
