---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ckan-credentials
  namespace: default
spec:
  encryptedData:
    ckan-api-token: AgCQcIMRtDrmfq/qN/KzT04Zh70Z960DR/xGj/FVOo7d9HPiYuAm0yzSQ0IRJsm+ZWoWIFayKzBkGU4E6oEBi1kW3c+mZohLZK8Sh1LkkKGTFp8Eyz2gOXAusbWiYlIINhGKl6XUMYJofmhOa2Lt9Ffxa6gkO0QXfYvlb9CIlkLzzW6nk4sQmebm6aqF5b68zpFgvnAYDA7ULbuKZwN42FwuGbFkAJz8Yy9++bGSwLxpjPvBv6YL4PxoCpn1DPWXVDcJKtHScMVxFirAx2iOAYABdhhkTfPBHpgb+9e0qZeoD725SA7CzVnDpr6sjymr39jRvjRL9h0IkBcZaZtXpCo3dQsbua5uCRQcwhlhXt0vghjhJij1JlRQmC14TVtCPz8zx6/1Q5VlLYpmo3+A2lUJ/28VgqZm6zZ37dCFzSlsvrZX/rK4i7tvuTv+y4Xa696+QcYrG+OcrGNoNwlBKN4wG9ptMLLt9X6gowEOlHeIgjKRH1DW+FCHvyi697wUrAO82d/73awJ//MR05Zj70RSxz13AB9RIu239YPU/RD172Jk0qMYsKMsqt3UTMbf5kZFLxHuua20F4Fnz0K+U/GkccJ5ok4PxeBmfS4Pe4lvsBZfFfHIneZDDTKRDFtTv0+mazieIPvKAr8VovWAy5B/7N4JQBlS76mTTJlzMjRr7vXpZXucoWb80X9xoT2MHuiXPxF6g10/CXQ79X4VvGto2PrJ9QBI03C5xaa7MhWx7gxfYd3/DGIBHE9iNjt73JABydZytSSZj5C1gzJTFcltFK++0sEWQG5l/2VJJaKR1i9Lf4Mnv8Al7Q76hu/6gg7B9YQY9oLBQBwwsHs7Y1XpBJH0izXxq/pkwOIaqVOvEfr+spARF5PbAgu9WCHjIBjSJ69A8bnKfmhn97PbI6fB/Cer+8tfjc0IPUnV5rAM
  template:
    metadata:
      name: ckan-credentials
      namespace: default
