---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ckan-api-credentials
  namespace: default
spec:
  encryptedData:
    CKAN_API_TOKEN: AgBTJMvXgrBMTyNY+QnJA5ygZTShuKXAwliHDtU4W0Oxr27HH/rKkcWa/47040UbpNh0imnZEAOHfdE8x2gqOaSOwxzuNtULfABfQyZBacdByZXCqI7+qmq3kEGZy0Qh/jQdmVqMET5dZjJillolSP1v3MdyCTnUvYpGQhWKtmH1axHmVZGHpwWbriAU00sbHBGFC1lK6QMxFjeHCYatYoFr4FCGZ7C+ScpFNIH9eaWcabBpN2C4TvvnoQjk7fvEwycgBKlzx7UQi0P5j6r0Bul/RvFULBb1RzVWkPKSzs+3wXXk6QIE2DUUmjTrcFrQ/ei2wwP3PkA2Dcez+pP7SWYLYuWEf6b+urE/KsEIppX+7xKH72hFL2JO+91ivOMX8+pjZ1C/kP1WjMgfYjhCnlaI6m7cb23ui+H++uBjxiOw2yK3E9HhECvra0Z8MLM/iGj8M8malSQrrmeNY4h3kvcLMLKu0eD7dIR96lIKL62zyo6lmzf7oObxM6aP65pAJy24q10apeybx4X7WA3wfOWHK9L0xtbNFlwUGxWH9UXv5AqQF2dFEz1PA3yUZqEiYeNMgmpZqNCZwOj/I6WMYGiYkM9Vn95RrzZ3nSrlQ+AORlHSAc9RUYRjzeXiMr43olm0FKIy7uWQJbrRFOfOkwv/jpGsC9RmgZcRxRtHWjrwfoB40zBFBNh0gwa+9LT2crT40DtghhDl8KeM4rsqJgA4cB5jA4aBq0OZ1dLvZWBRPzD1AUli+vNwRE9UJ0/ANl4d+YamQg++XXFYgoKFHy/mPGCQwyomiLJzYNHIt8/G0FrqFf6X9mv9DicU6ldFVvVovLGz45pkt78MFieFiVNH6oGimgQB+o+qOTwKWAnzWMCnBM2b9uqAYHVbfPTJjD77S1EqxFDSo+Y2mpbNkgvlueIANYMtNmWYCDCWlTu6
  template:
    metadata:
      name: ckan-api-credentials
      namespace: default
