---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ckan-credentials
  namespace: default
spec:
  encryptedData:
    ckan-api-token: AgB9LJrAEpRYFcruxD2bs2ZjD98R5j7NKwqtlQDHzVf5VUp+dTQH2ipep8p43Kcl05RXJdnhSUw0TYpHgEMtVkN3h2T8z5ZOskknj2Kl3jFXVZfYV83toKwE2i16cwaoz0Rb0Ec/wzHAxyQ+Fv4Kc/60+Wt1/1gtfUdyYhiDKQnr+IVCRYJnMShl9/UFX6vPb8tLpV71FRmCoUk8MSg1IPonDNqE5FyHfqdUWwSJlvxvQUZZtlhPiKUUOgtqejU5PKDTrwbJJueQ6T0tU139GA1akoj0WCwJZN/6uw/L84NSJACTt6ZICH5kuYbfThumMy3SHVEukjyMK3y5SZ2LZ8JRamVrorBhEU/01PW8FOk7QkKkaJvt4oeofWeTJo7dy0ylVRuh+GA3cr+9yt9XIqHMOYG9175Trd3Wl0WvZaSHpSclS7MFegOmcwKxokcrHB9W+HT1LZYfOCZgByja9RO1rMs9QWvOg8NSMr3gadQZj56pI7DypOCutupDjvk72ViTMXXlzC2PAePqA/joHlqY9GqIKFukB75Uh+NIvhfgjpqhE9HE1Ki2QJnCqitaPSXorWp5d7jUePpvMFyp1EQWimJ8U2CbGt/iCxy5f6r0k2TlPyfWkyD7Qa1PXZQs3mBFllTAw9W17OGSUSPdbFuExSfPerYjjdh4ilWXeLDRTjAatuIE4vneoYBqNtmzW3b236mvI2RkojyAlc3XYcF7rtKkcxhyfWKWfOO1MRvStKsuf1iD3k/HQm4Gmf6hiMxMKWZmLleEWmjC0Waf8kTeL5BrmnCVAH71QMxF3CWBv50VL6rijT514r2Tme+I13E0a948Ufb8ZaLLwRqMBF9HMZrSGzeyg5KRewV23HFpYHhIjZcKcZQW173RXpnLspCMtPIixJgXmzpo6eTPFFrtbHMswFG5XcgyPxKiPtN6
  template:
    metadata:
      name: ckan-credentials
      namespace: default
