---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-credentials
  namespace: default
spec:
  encryptedData:
    github-token: AgBw49caPhv+ckDXns5zXM3RnCG4eI4HFqKvA6lAUoheMA1odQEvpzp7+gwMix93Wn1+Kh5JuMlRgORQc6vK5uEXk0TIgF9fF3S6PmKGJbf150aL5REWrvDv3fcejgHt1W1V02zn0kwwUvgBxxujuoyUV6/gkUnCZI25X3he78ZPKXDbgqsPx5GKL4oFTk0YteaU5geDbAa7qq8CG6OyKWZRFTucJQWUNwI/SSGa8ERHDzsQhqeTPSwmwRXVglGeOJ7/QglTL5bD2h93Wqs+2V1XoEoL37vhavHdtfHwSfAgE5sFw+rRBjZQ9qYQxS3kw/hNlxvgDpidvdG87CfhdSGi544MB4krNrVX9CMZ6KsvEWIgo0Knn8bOHWMEyUH30eBfiT+PcU8iaVhjYLdv0p9S6zaBuJOYFzyJpFZPzb+8wTL7RDQ4/erc+8Bft6agOZBgCFwWUYktjsVgwYZswyKMpDhJdCXa8OiibrEL+A3Rt64afsJbEeXRTwgvYyxcuqsdYABPbzNxXceIx3MCvevFf2UIs/iadNEh73QTP86EVyjPaFItWuHSHQlVuXOzOA9cQ3ORyofW1k6bA1gnCOAC2EPN9dIbAQLpnyxY2nxJA16OjOWUmPMiNmxj8u8daQarprOwebJ2T8FFRsCpBQFbgPE3iOnYrFniAHYrJDnQHJuX/+/jHeRjL74t5F7CJL36xcBLLxOfM42V/qRJxG7Fs9p6PtgOyLgJ4oKqCtTgU/tkfBPJtsg5HhYY0AsTsABw5JVEXbZSz6WcbQFkMfeFNMhSViJ4n82fiUXpFqCdDvDiOUpw7pAQjf+GF8M=
  template:
    metadata:
      name: github-credentials
      namespace: default
