---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-credentials
  namespace: default
spec:
  encryptedData:
    github-token: AgAXp7SEbfLOLHkWDPoBSwb4yS68SMvXgpHgSkNEX+zoOCAtZkaYTcaPc0kO5Tw+65O7X+n83b1xpJxO2Z6taG+PsgsoKl2ERf6mXfS+eSAdYWTghoE6DtV/ewJRvtjgVlbhvWgOpXwgL2ss29SNjsvFIAMY4IHxGbbFYWPUhh9c1sRaNcL7kkrJwCUpIh4Zv8dS3p7JLT56ozgzMuMrVn22BxrmFcqGsXCKvN6+DZMNJeXuA5OEuk93nB+SHzkNsZWynVaEsxua4/Rkw3NXUbRgaSxfTcslshh4CLkMvVxFZt9d8xunf4gHJFyr53QYmp2DE3viSihx2JK+K7x/Yb4CJWbxTJg0kCAE8EWuLXZQnB/ZxL//Eu++JrECZcaTsTr65qG+p+EMAhRt6yC7N2EagC5H3BPmHCgNv12IwlYp+svkZm1wJW+UI5TNmWcGsyNiKxrqDKt/KzAN0Mmkdpe29vHjenufrg80nnTxBL7FMb3wbQsryfCA+/cBIagHfiIoXbCeka+A2dJ82VGLV7DcmOkeckwgZm0QKGrcE/JojbN/zgBXBs4XH86K8xhfqEFLMfc5/vi1E2VMfdpQm2WPikGpZ5ZwOL1PZipDB+Mg2s5rCAP+56cW/4sy4GW+AONSTSFHLlLfZJLPKCUepTGZriYt/nTihPXaosZ+JcZsnlQTwxix0dAcA0a/O96FZS+M7oZqm01ouO7ptptflT0GHpxDROzY06nUBN/pcYmcU2d5ffTW3Ap4zKtB2CQLjptoD2QOUs8yvHigFWL6TUgBx4HULtnybVThAeIWRux2RdIT2DVvGWlNYKNbcxE=
  template:
    metadata:
      name: github-credentials
      namespace: default
