apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lakefs-sealed-secret.yaml
  - ckan-sealed-secret.yaml
  - pi-agent-task-sealed-secret.yaml
  - blackboard-sealed-secret.yaml

