---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lakefs-credentials
  namespace: default
spec:
  encryptedData:
    lakefs-access-key: AgBwf/tOmXJ7/o2Iq+muzcySZZLIZCjDGLQAN/uzM+RjVTryragh5BJt1pFzwI+jCKlU8bYSGeqnadQoZxI1yNvpo21O7D8choulS0qoS9W0SMG8e+X97f6GvFzvYE+hVReuSZNSKHQl7QIxTWJ7hoov8xw3NPDe0Zgs0YEqPiLkjjZrBnwV0/B94WmQCZO07f0ShDa+1CDWWwTw5dqJhUHvjYxVeh81HxbKqxbDqlI/tliKS3rG0uVNbLwXwXeJxCAmXO1QO7lxRf6kqIEaLttWfJmUkTah2FBngnQoRT+P7fZrToMYtd4PIa+4Fh9MVFQUsLksgd31446HzIVe0xWPDOuqLOj8I7x4xwBBNa3Zk1Jz6PlFROv+CnQJNGGMjf2nzXAY1u6pNExT0PKMbE73vegWOwToHftZzr3vGhenPvGq+W6v3jSQOTCTlFSJ55vooKR07yvMSVIhRqwLl/sz+1kbS7YDFfOkVNfGeldiKCy+Vw1QHzF7NQjXg5tIGzPF2luoGz5CdHose1M8S/0IqfTUlX2pQAr9dQxa5L/05fHBx9M5fCMptmWi/nAMcdT2qvBm5WitQysup5+J5P+fPw9XqCiGEQfBihpY5rfjLa0DlSKYXr/eO5kIzvAPv2xArgMGJrX3qhC7MTBbEWudAOpoXeKjDnf6L8EDY+CYqTmiC8X/jReYTjLnrz/Fd0QwZQGO0OlMtB5o4Hu4rFpVI5FX6A==
    lakefs-secret-key: AgAiEQeElQvCyNOUhj4kEwbQ63hTDig0kNsNbKti+2HSikw8vKWumFa8GMAOW3G0ru/EsCscxQwUAxDUqlFck4mzOc63zKpu4Xoth5dQYzjgNsCdUfCbtbhryPetxiX7tcUPhmYvP2A+M4okDza4BtcrftngBOYjyh5TlWLRqqgvBE+i4+OWRlm97ZPDGazC08O7g2BnUqTv4xzzZEzE+hQQQU7Op1BEMkOMD07LD4LfQzh9qpmodqiFPOmq0xrXQnDjuMBesCb9Y7Y0oFJ3PL6vcvzR42xblxJ2J6zLyCkz2Xr6+yayG5m7rG2hndL3yFmdD59wNYcJ9lgws4nPqH0UGlwi8dMBJsAhrT19BEPmH1ekioq2vDfOPPvU7sK7mdoxMEgUAkKBfRvjkUi/sC/BPza8BFxwLPZYg/6s4HUKAo3Drxfwe4jAlZ+EA7a0W9hlo3mLIdwyP2nIyKZaCjBttC0cJdds2hDL5JOcd2NkCjcG/J4Z00NdCAeArDvfPiLcSHDyg9Qq0VTwpBfDNhNiQaUlxmRQ2oYDXe9SnaTVKb1QjIgcV9Rb3TW0ctVcjt4cxuoWzIGeY67ywMeVpEmHxiJktKLwLHfZepfDBxEAuBu2SVhJMtlfnc0oWZIxpouCHBM82jynRVa04NikfVhABy08G/ZsMEuYSS/Qy3KtB9ImP0CWIoPYAikodtEIjM5kFr3KlSVY57eJqOoxUfCd0yBWQBRLtxsxj/gisQ+ecV3GlFlhwDRh
  template:
    metadata:
      name: lakefs-credentials
      namespace: default
