---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: typesafe-credentials
  namespace: default
spec:
  encryptedData:
    typesafe-api-key: AgCPsV9rYhRL6JMHPteiwYSgY4B464pQz0jYSsiciZrEp0/iG++K6kIFqJ+o5dtqPvlMCLmi07Zv98g1SIiGy/JkD1acb03L7rJFTYOFDp3Ef5MgprC6SGHMk8HVNZN3EryCIhiRcaagH4CDCzFcS4FTJ7JNuUbvvfqHm7lRA5T77DMTc3hWMdGjG4545dh/hxoOnvreP2a0vIqymgsX5mBnfKyRraKh1k1q3alKKLU5fbXvhydY/tT1xYZEQkVOd6z9W4uURE9HzhpqCWaAGVxBpVo1iew9uop33Tk9m7doz6Ni4ntPyl1h841mKap9dsWuWi8dhoBGcU4pnRvd/rmJhsVdOVNKsio86C457xrkgqHcsvSNrBwY6E8JQ8tfCjU+L5QmZJ3fwQDC/qxLQj5XecV7JO72dE2iBR8kvw2f592oCsLXRt4GAK3larvi04+ahlSRm+8IP4sHNmrXa52dw7hIqlto/8CP+VPBYia+aQg6GSG+UqwcMhAb0GpDedH3nHB/DZ97ukQn9n8ea/klv9b4g8jtuLYR1jfbC1mxPSi8weWrXOUYcarHwUf02Ck7Fhj6vwLWt7xAvBjdGnhWbxibBk1lBCcqmOw05Ofvzcyi059gGofoJcuf7Gan94EzhOTLRWyymkEeDFGAaiyKxqGR2jL1oyKQpVZhK5oKCncyyKrhvA05URSFtgRzK0BQn0yVt46S9lAW68fsvzEwcq9M0nAkwrLNX2/eaIXI3LJ4Ps7d1adOg8vGV9Ay3FtWnOxr2XYZy6obdcI7NfqLvOGsuoB/PceeS9zC1B27XuyePXjgtVHu5sqR6d9CS5Iegs884J05zWlllHw=
  template:
    metadata:
      name: typesafe-credentials
      namespace: default
