---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prefect-db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgAnrMW0uUoM9HE86Q/cZy90EvV0NexOl3hH6lcp3a9fz9LooayyomKFaq3g1X2HdimP9GxO67A322dRQoTiIkSdQEoSYg4x4t4fO2b4LPj+1nyPYli1MLW1/cLKNu0bi6WZXtaf6+cXFHUPatgEjwXGqeAllwCsYF2NVkEnaTiN6IXI5FCSFU+xpUCNMbUVDMJqWa0XDjDLEZtzHY2NH/x+EI/7VO1tHeQkFV0W/jVeYPur/kWBhhjUycl3I0R0CBa/RvCROAVM7P6kLHxvBv3DUvexiZtXCQVBbjZZUg0GBgJcWY7ilFtNeY19CR76c+5rQbRbHoLiuTHYMNaWDe3dcSDXpQwXkDUZ/aRdlg7cLJCmW5fbiESrl6rvAOFE51GTChdZrPXHgOpE3ju1g1c4iFHQisM3R8bk5Pel6cOrhmxkCOlQ0KXlKntNxtoh49UcGKk/vaUyNxxVfkvJpw3hb7la+N+oM9Q4NneBfSnsiW7fm3/cyF3FErtSXMo7hfE/mzYufUB9V6DprL6f+p8X2JfcouPeqtxlxOndsdfkUJ4nyvq2y2aoGmVQj2HEB2hTZ5NY6ii0ZZILQjVmhNTCbEMRtJYrjyyIkZG1S2Do4U1LKtqrKojnTDwgTK5OKwsL190096dmhI4HhXKRU5CPb+oivzfSRlvFkGqMgRnuFE4S6xOrB9IKwW4vvlOL9nro1VhtIaxgVcqXxv7vhv0zXXU/D0mPxHn+oGiBLcG6MQ==
  template:
    metadata:
      name: prefect-db-credentials
      namespace: default
