---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prefect-db-credentials
  namespace: default
spec:
  encryptedData:
    postgres-password: AgAeRpgA3j831nXMXTJcn018xZMomSTAeYbzrlhfi71zTN9BzA8rFUBWdhsEUb61wbizwSDpRbnrNbl8VCEmUACKWEO4TzctWyXgK37Jb164MS1YD8gGgy7XDNJBH5TbUr0YiU1t6a3SvwKxLS5awfcfb9bTiHdeS5zAu0v4UL+5pf2TM0TRxegCA56aNkY41q3Ef0aP/N7CI/BwL1Wd2wjTMg594EjrT3fYKetsha9IhmrLTbCFQ8TaNn3dMOhrTcnPHEjOUgW3Rw4bxUe/alIQtONV+DXP0CP+ipUTJ79HiSqZ3l4MEo2/iS37+undn+9IueX53OBAY18+JSU2+Q/h43JJxee7wRIeSvq5sF7EUmS+klRZZbhucIKtHsUdwBWy4+b58wbGXW4ZJmUP1wfSqFU5vYk16s6Zq/wNqsM8YTwUMqCu6r5Ceq2R7QrLvsbe4v9VcDs1l5rgfSJTcgogVYV37IkdJBvSUlrTru07uJJ72h/fL5RL+CYQnz0gCfjOfArFxUFtPpaUZBNGaBwrVRI0MdwPAtKDRoWU0xxZ2OnYVAp5/9+Q8z+L9LIXAXV54IBO2nHi25TGJsyt9VGAu1twGDWyLqpZFHplNa5D+Tv56X/AbN7gyVDw+FKRynbi64G/8VV3fCqF3dOCWoxcJ1znh08fHePowIUBi8h7uWl61qAwf/li9nO0aIKce5erFFv7uAxft8KfPUICXxtPfMrN3Urj60QQB2M8bnTCmg==
  template:
    metadata:
      name: prefect-db-credentials
      namespace: default
