---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prefect-postgresql-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCjEQQeYjG5w1ofhOWW26Kv83lZLcgrL7fzIwoDbjBrJJu0VufMjbvKLKgZV/evem88JLx3iMj5tJm1+L1P8aarwPW6W4CVbjn+N9U8EJwgtg6S8STqZLe5yH3KNIfPl1Zzbh8b7UtYfWy/7R2aNK9DBd6tynFA78P035s/u+Qb4i0LvVGmR4NIvgAgaz9fMNazBm3ZU7JQfQXU4qVbpeq68QcqZWNjEPiRGFmiGBwxZyyOn78+x/J4gqR25hNoGSmvgOt1yS2KSyzW3CtzxDBSUxkUcaqk/0YOY7dXTvUzTckI79fJRWs+7Dlgt21KS7VdIxGfl0w/fdMEVTOaJ3aQipJQo6eFWC6CAl7jeoAGPbixltvcx7ppEiNveIM1hCmhEvbpbI/Wum3ns6S3H9SpRwI/7G7/FfeqIzyg1jPMPFNf+QdMc7tWbde8HK4dpnsCaTChxglF3PwGacuCqsipmftQaI69PZUzhLvsPURdfSmbmQZoGJ4Qs0tJisorj1AfI6Or50KY86aOwPE+yEJhBWKaY4bTAK6YgykBWvviIswrSI+HWVpn0LfhtGFdX49GsrlXbDf2gzOlIWKdQXCCHjFBhBFpzOXLswIxdUHNp7ckdNx50ZIuGcyPFBgCVcdnpTaKTXt0FeuqBQew0n/hwoJJ29xzpYXex2zf0O9t3cxnWYHE7eLDppeXw1M38biiV+fg8erEuFs9qwA6C/Xn4l71m8wypd3vSGL5tlD5vw==
  template:
    metadata:
      name: prefect-postgresql-credentials
      namespace: default
