postgresql:
  enabled: true
  auth:
    username: prefect
    database: prefect
    password: "your-postgres-password"
  primary:
    persistence:
      enabled: true
      storageClass: csi-rbd-sc
      size: 1Gi

server:
  env:
    - name: PREFECT_UI_API_URL
      value: "https://prefect.episerve.zib.de/api"

