apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: prefect-worker
    repo: https://prefecthq.github.io/prefect-helm
    version: "2026.5.16021822"
    releaseName: prefect-worker
    namespace: default
    valuesFile: values.yaml
