---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-smtp
  namespace: ckan
spec:
  encryptedData:
    password: AgCTjlUO/7IzTGTO01RaccwBcs5OOjHSKwL7kJ9JoAtlR83deOVH+IVsFwvMOHKmW7FPH7nYoMR95yO0iFylgqsY8s7m0TDPcp0BslrX2cjDEXfkazSCEEokL3o7pIDd/hflaFl/IWB9Xvx6AWiJg1WpM/Jh/J0T7IWhjyq+Qo7psUTp6pJY7Ex/RKU2pq03z3BxpQ4s7O38RjmyU0ncHnj5TcEaRiHOqyvbDHMliu6L/U0ZZe8Q/jrQdbOsZCy4kWpzMd8MPyJOT4gkWzL/4iZ7dw3snGZe6UEl/mOqx3yNwKiZI48maxvgDSh+Cm+b7w6igrqiPvplqg9HfWUkT3juq8yZvYXfKVlIbj0X7TEFbv+T6VtJYamJ47a1NtEVzzbmJPt8d7b/bZDb7SN7JwRnuya0nWdklFcYZiHVd1UJe8N4MYCaimjc/0CZJT6Ayl8BpartZHxxM85HvizdpLA309WUYsFOZkErooMGqJUAuwdN9eag10anH/lO20KDd9h1u8BXZQppSvcmCASh9ap66HUx5eoaeRl7MliM1jenwI5CooptMzLQeFJQgjMREb3R5ARsfTiSZhuNsCrJu973Z6DSC4PtwykfbHrr6Vvsty0cAnsnd88vsVrlEgqmyqnXYpaRRwH8V2CPQgQFPTmoLVer5WxE0AaIfb0K9EGFhclPbXaUyQXD2dZXzbUdZ8WV3BmV7kSTOU46d682pWzEZDiR
  template:
    metadata:
      name: alertmanager-smtp
      namespace: ckan
