apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - trafficpolicy.yaml
replacements:
  - source:
      kind: ConfigMap
      name: gateway-config
      fieldPath: data.routeName
    targets:
      - select:
          kind: TrafficPolicy
          name: zib-only
        fieldPaths:
          - spec.targetRefs.0.name
