apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ckan
namePrefix: ckan-
components:
  - ../../base/gateway
configMapGenerator:
  - name: gateway-config
    literals:
      - hostname=data.episerve.zib.de
      - secretName=ckan-tls
      - serviceName=ckan
      - servicePort=80
      - listenerName=ckan-listeners
      - routeName=ckan-route
