solvers:
  - http01:
      gatewayHTTPRoute:
        parentRefs:
          - name: gateway-acme-listeners
            namespace: argocd
            kind: ListenerSet
            group: gateway.networking.k8s.io
    selector:
      namespaces:
        - argocd
  - http01:
      gatewayHTTPRoute:
        parentRefs:
          - name: gateway-acme-listeners
            namespace: default
            kind: ListenerSet
            group: gateway.networking.k8s.io
    selector:
      namespaces:
        - default
