apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your@email.de
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: argocd-acme-listeners
                namespace: argocd
                kind: ListenerSet
                group: gateway.networking.k8s.io
        selector:
          dnsZones:
            - argocd.episerve.zib.de
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: prefect-acme-listeners
                namespace: default
                kind: ListenerSet
                group: gateway.networking.k8s.io
        selector:
          dnsZones:
            - prefect.episerve.zib.de
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: metabase-acme-listeners
                namespace: default
                kind: ListenerSet
                group: gateway.networking.k8s.io
        selector:
          dnsZones:
            - metabase.episerve.zib.de
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: ckan-acme-listeners
                namespace: ckan
                kind: ListenerSet
                group: gateway.networking.k8s.io
        selector:
          dnsZones:
            - ckan.episerve.zib.de
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: doip-server-acme-listeners
                namespace: default
                kind: ListenerSet
                group: gateway.networking.k8s.io
        selector:
          dnsZones:
            - doip.episerve.zib.de
      - http01:
          gatewayHTTPRoute:
            parentRefs:
              - name: openproject-acme-listeners
                namespace: openproject
                kind: ListenerSet
                group: gateway.networking.k8s.io
        selector:
          dnsZones:
            - openproject.episerve.zib.de
