#!/bin/bash
# Generates sealed secrets and initialises the CKAN PostgreSQL databases.
#
# Run ONCE after a clean install before pushing the ArgoCD-managed CKAN app.
#
# Prerequisites:
#   - kubectl pointing at the correct cluster (CKAN/postgres pods must be running
#     or at least the postgres StatefulSet must be up for DB init)
#   - kubeseal installed and reachable (uses the cluster's sealed-secrets controller)
#   - openssl available for random password generation
#
# Usage:
#   export SMTP_PASSWORD="your-smtp-password"   # optional, defaults to empty
#   ./run-bootstrap.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SEALED_SECRET_FILE="$REPO_ROOT/apps/ckan/sealed-secret.yaml"
VALUES_FILE="$REPO_ROOT/apps/ckan/values.yaml"
NAMESPACE="ckan"

gen_pass() { openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32; }
gen_secret() { openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 43; }

seal() {
  local name="$1"
  kubectl create secret generic "$name" --namespace "$NAMESPACE" --dry-run=client -o yaml \
    "${@:2}" \
    | kubeseal --namespace "$NAMESPACE" --format yaml
}

echo "==> Generating passwords..."
MASTER_DB_PASS="$(gen_pass)"
CKAN_DB_PASS="$(gen_pass)"
DATASTORE_RW_PASS="$(gen_pass)"
DATASTORE_RO_PASS="$(gen_pass)"
SYSADMIN_PASS="$(gen_pass)"
SOLR_PASS="$(gen_pass)"
JWT_SECRET="string:$(gen_secret)"
CSRF_SECRET="$(gen_secret)"
SESSION_SECRET="$(gen_secret)"
SMTP_PASSWORD="${SMTP_PASSWORD:-}"

CKAN_SQL_URL="postgresql://ckan_default:${CKAN_DB_PASS}@postgres/ckan_default"
DATASTORE_RW_URL="postgresql://datastorerw:${DATASTORE_RW_PASS}@postgres/datastore_default"
DATASTORE_RO_URL="postgresql://datastorero:${DATASTORE_RO_PASS}@postgres/datastore_default"

echo "==> Writing solr password to values.yaml..."
sed -i "s|adminPassword: \"REPLACE_VIA_BOOTSTRAP\"|adminPassword: \"${SOLR_PASS}\"|" "$VALUES_FILE"

echo "==> Sealing secrets..."
{
  echo "# Generated by bootstrap/ckan/run-bootstrap.sh — do not edit manually."
  echo "---"
  seal ckan-db-credentials \
    --from-literal="postgres-password=${MASTER_DB_PASS}" \
    --from-literal="password=${CKAN_DB_PASS}"

  echo "---"
  seal ckancredentials \
    --from-literal="sysadminPassword=${SYSADMIN_PASS}" \
    --from-literal="psqlMasterPassword=${MASTER_DB_PASS}" \
    --from-literal="smtpPassword=${SMTP_PASSWORD}" \
    --from-literal="ckanSqlAlchemyUrl=${CKAN_SQL_URL}" \
    --from-literal="ckanDatastoreWriteUrl=${DATASTORE_RW_URL}" \
    --from-literal="ckanDatastoreReadUrl=${DATASTORE_RO_URL}"

  echo "---"
  seal session-secret \
    --from-literal="jwt_encode=${JWT_SECRET}" \
    --from-literal="jwt_decode=${JWT_SECRET}" \
    --from-literal="wtf_csrf_secret=${CSRF_SECRET}" \
    --from-literal="session_secret=${SESSION_SECRET}"

  echo "---"
  # Placeholder token — replace after first CKAN login (see post-install steps in docs).
  seal ckansysadminapitoken \
    --from-literal="sysadminApiToken=placeholder"
} > "$SEALED_SECRET_FILE"

echo "==> sealed-secret.yaml written."
echo ""
echo "==> Waiting for postgres to be ready before running DB init..."
kubectl wait pod/postgres-0 -n "$NAMESPACE" --for=condition=Ready --timeout=120s

echo "==> Initialising databases..."
kubectl exec -n "$NAMESPACE" statefulset/postgres -- bash -c "
PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres <<EOSQL
CREATE USER ckan_default WITH PASSWORD '${CKAN_DB_PASS}';
CREATE DATABASE ckan_default OWNER ckan_default;
CREATE DATABASE datastore_default OWNER ckan_default;
CREATE USER datastorerw WITH PASSWORD '${DATASTORE_RW_PASS}';
CREATE USER datastorero WITH PASSWORD '${DATASTORE_RO_PASS}';
GRANT ALL PRIVILEGES ON DATABASE datastore_default TO datastorerw;
EOSQL
PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -d datastore_default <<EOSQL
GRANT ALL ON SCHEMA public TO datastorerw;
GRANT USAGE ON SCHEMA public TO datastorero;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO datastorero;
EOSQL
" && echo "==> DB init complete." || echo "WARNING: some DB init statements failed (may be safe if re-running on existing cluster)"
echo ""
echo "==> After DB init and ArgoCD sync, complete the post-install checklist:"
echo "    1. Wait for all pods Running: kubectl get pods -n ckan"
echo "    2. Generate API token via CLI (not the CKAN UI — see Known Issues in the runbook):"
echo "       kubectl exec -n ckan deployment/ckan -- ckan -c /app/production.ini user token add ckan_admin workflow"
echo "    3. Seal and update the token in both sealed-secret files — see docs/2c - App CKAN.md step 3"
echo "    4. Create CKAN data model (org, groups, vocabularies) — see docs/2c - App CKAN.md step 4"
echo ""
echo "==> Sysadmin password (store in Bitwarden now, it will not be shown again):"
echo "    Username: ckan_admin"
echo "    Password: ${SYSADMIN_PASS}"
echo ""
echo "==> Next steps:"
echo "    git add apps/ckan/sealed-secret.yaml apps/ckan/values.yaml"
echo "    git commit -m 'chore(ckan): seal secrets and enable CephFS PVC'"
echo "    git push"
