#!/bin/bash
# Generates sealed secrets and initialises the CKAN PostgreSQL databases.
#
# Run ONCE after a clean install before pushing the ArgoCD-managed CKAN app.
#
# Prerequisites:
#   - kubectl pointing at the correct cluster (CKAN/postgres pods must be running
#     or at least the postgres StatefulSet must be up for DB init)
#   - kubeseal installed and reachable (uses the cluster's sealed-secrets controller)
#   - openssl available for random password generation
#
# Usage:
#   export SMTP_PASSWORD="your-smtp-password"   # optional, defaults to empty
#   ./run-bootstrap.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SEALED_SECRET_FILE="$REPO_ROOT/apps/ckan/sealed-secret.yaml"
VALUES_FILE="$REPO_ROOT/apps/ckan/values.yaml"
NAMESPACE="ckan"

gen_pass() { openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32; }
gen_secret() { openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c 43; }

seal() {
  local name="$1"
  kubectl create secret generic "$name" --namespace "$NAMESPACE" --dry-run=client -o yaml \
    "${@:2}" \
    | kubeseal --namespace "$NAMESPACE" --format yaml
}

echo "==> Generating passwords..."
MASTER_DB_PASS="$(gen_pass)"
CKAN_DB_PASS="$(gen_pass)"
DATASTORE_RW_PASS="$(gen_pass)"
DATASTORE_RO_PASS="$(gen_pass)"
SYSADMIN_PASS="$(gen_pass)"
SOLR_PASS="$(gen_pass)"
JWT_SECRET="string:$(gen_secret)"
CSRF_SECRET="$(gen_secret)"
SESSION_SECRET="$(gen_secret)"
SMTP_PASSWORD="${SMTP_PASSWORD:-}"

CKAN_SQL_URL="postgresql://ckan_default:${CKAN_DB_PASS}@postgres/ckan_default"
DATASTORE_RW_URL="postgresql://datastorerw:${DATASTORE_RW_PASS}@postgres/datastore_default"
DATASTORE_RO_URL="postgresql://datastorero:${DATASTORE_RO_PASS}@postgres/datastore_default"

echo "==> Writing solr password to values.yaml..."
sed -i "s|adminPassword: \"REPLACE_VIA_BOOTSTRAP\"|adminPassword: \"${SOLR_PASS}\"|" "$VALUES_FILE"

echo "==> Sealing secrets..."
{
  echo "# Generated by bootstrap/ckan/run-bootstrap.sh — do not edit manually."
  echo "---"
  seal ckan-db-credentials \
    --from-literal="postgres-password=${MASTER_DB_PASS}" \
    --from-literal="password=${CKAN_DB_PASS}"

  echo "---"
  seal ckancredentials \
    --from-literal="sysadminPassword=${SYSADMIN_PASS}" \
    --from-literal="psqlMasterPassword=${MASTER_DB_PASS}" \
    --from-literal="smtpPassword=${SMTP_PASSWORD}" \
    --from-literal="ckanSqlAlchemyUrl=${CKAN_SQL_URL}" \
    --from-literal="ckanDatastoreWriteUrl=${DATASTORE_RW_URL}" \
    --from-literal="ckanDatastoreReadUrl=${DATASTORE_RO_URL}"

  echo "---"
  seal session-secret \
    --from-literal="jwt_encode=${JWT_SECRET}" \
    --from-literal="jwt_decode=${JWT_SECRET}" \
    --from-literal="wtf_csrf_secret=${CSRF_SECRET}" \
    --from-literal="session_secret=${SESSION_SECRET}"

  echo "---"
  # Placeholder token — replace after first CKAN login (see post-install steps in docs).
  seal ckansysadminapitoken \
    --from-literal="sysadminApiToken=placeholder"
} > "$SEALED_SECRET_FILE"

echo "==> sealed-secret.yaml written."
echo ""
echo "==> Database init commands (run after postgres pod is Ready):"
echo "    These create the users and databases that CKAN expects."
echo "    Copy and run in your terminal:"
echo ""
cat <<DBINIT
kubectl exec -n ckan statefulset/postgres -- bash -c "
  PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -c \\\"CREATE USER ckan_default WITH PASSWORD '${CKAN_DB_PASS}';\\\" || true
  PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -c \\\"CREATE DATABASE ckan_default OWNER ckan_default;\\\" || true
  PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -c \\\"CREATE DATABASE datastore_default OWNER ckan_default;\\\" || true
  PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -c \\\"CREATE USER datastorerw WITH PASSWORD '${DATASTORE_RW_PASS}';\\\" || true
  PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -c \\\"CREATE USER datastorero WITH PASSWORD '${DATASTORE_RO_PASS}';\\\" || true
  PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -d datastore_default -c \\\"GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO datastorerw;\\\" || true
  PGPASSWORD='${MASTER_DB_PASS}' psql -U postgres -d datastore_default -c \\\"GRANT SELECT ON ALL TABLES IN SCHEMA public TO datastorero;\\\" || true
"
DBINIT
echo ""
echo "==> After DB init and ArgoCD sync, complete the post-install checklist:"
echo "    1. Log in to https://data.episerve.zib.de with ckan_admin / <generated sysadmin password below>"
echo "    2. Generate an API token via the CKAN UI"
echo "    3. Run: kubeseal --namespace ckan and update the ckansysadminapitoken entry in sealed-secret.yaml"
echo "    4. Create CKAN data model (org, groups, vocabularies) — see docs/2c - App CKAN.md"
echo ""
echo "==> Sysadmin password (store in Bitwarden now, it will not be shown again):"
echo "    Username: ckan_admin"
echo "    Password: ${SYSADMIN_PASS}"
echo ""
echo "==> Next steps:"
echo "    git add apps/ckan/sealed-secret.yaml apps/ckan/values.yaml"
echo "    git commit -m 'chore(ckan): seal secrets and enable CephFS PVC'"
echo "    git push"
