apiVersion: gateway.kgateway.dev/v1alpha1
kind: HTTPListenerPolicy
metadata:
  name: shared-gateway-websocket
  namespace: kgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: shared-public-gateway
  upgradeConfig:
    enabledUpgrades:
      - websocket
