apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openproject
resources:
  - namespace.yaml
  - sealed-secret.yaml
helmCharts:
  - name: openproject
    repo: https://charts.openproject.org
    version: "13.6.0"
    releaseName: openproject
    namespace: openproject
    valuesInline:
      ingress:
        enabled: false
      openproject:
        https: true
        host: project.episerve.zib.de
        admin_user:
          mail: "admin@episerve.zib.de"
          password_reset: "false"
      postgresql:
        auth:
          username: openproject
          database: openproject
          existingSecret: openproject-credentials
          secretKeys:
            userPasswordKey: password
            adminPasswordKey: postgres-password
        primary:
          persistence:
            enabled: true
            storageClass: csi-rbd-sc
            size: 10Gi
      persistence:
        enabled: true
        storageClass: csi-rbd-sc
        size: 5Gi
        accessModes:
          - ReadWriteOnce
patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=openproject"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: placeholder
      spec:
        template:
          metadata:
            annotations:
              backup.velero.io/backup-volumes-excludes: tmp,app-tmp
  - target:
      kind: Deployment
      name: openproject-cron
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 0
  - target:
      kind: Job
      labelSelector: "app.kubernetes.io/component=seeder"
    patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook
        value: PreSync
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1hook-delete-policy
        value: BeforeHookCreation
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENPROJECT_SEED_ADMIN_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openproject-credentials
              key: admin-password
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: OPENPROJECT_SEED_ADMIN_USER_PASSWORD_RESET
          value: "false"
      - op: remove
        path: /spec/template/spec/volumes/2
      - op: remove
        path: /spec/template/spec/containers/0/volumeMounts/2
