apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plane
resources:
  - namespace.yaml
helmCharts:
  - name: plane-ce
    repo: https://helm.plane.so/
    version: "1.5.1"
    releaseName: plane
    namespace: plane
    valuesInline:
      ingress:
        enabled: false
        appHost: "plane.episerve.zib.de"
      redis:
        local_setup: true
        storageClass: "csi-rbd-sc"
      postgres:
        local_setup: true
        storageClass: "csi-rbd-sc"
      rabbitmq:
        local_setup: true
        storageClass: "csi-rbd-sc"
      minio:
        local_setup: true
        storageClass: "csi-rbd-sc"
      worker:
        memoryLimit: 2000Mi
      env:
        secret_key: "YMNvQlertOeqCq9GlkwMdblGOm98ageBxGvPhMIOH9C0hKR_Uy"
        live_server_secret_key: "hbZ1RvW0XXtfPwX_hVVs01nUXbeNKdPCS-"
