apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
namePrefix: metabase-
components:
  - ../../base/gateway
  - ../../base/gateway-zib-only
configMapGenerator:
  - name: gateway-config
    literals:
      - hostname=metabase.episerve.zib.de
      - secretName=metabase-tls
      - serviceName=metabase
      - servicePort=80
      - listenerName=metabase-listeners
      - routeName=metabase-route
