---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: doip-link-secret
  namespace: default
spec:
  encryptedData:
    doip-link-secret: AgDJKGs29CRGlbAta6chZBcghwAIj6I0TgWXVeRj5psdYcfCmqLyo/ElqhJrjxof9ncW3x41LsrEZPmj188UjUAP4nf6c7Dtp9w9GiBKAjXZpPgevfY3icq6WPBmj4powkPNUMS3A1B3HzxFz6NPqRvcYiWpiekyY5ueIXEWo4U6Cm0FDGFR66aH+Kv4oWBi71HNV2Rpr5GRcwxkwGbvUddde4jXzBhI5M88nLn62bIBCUvz0e9qIoqeSLZmNb2F2Vm2UqSbrw6e8mRHpB7E9GlWiBaaCBm4mvchj8lSXfKO+XKC3ktX/AMgmiIccylrUme73gL7QkP7KgdXU8bhUdj4n7TyGadtdN+z2y9SGqCHLd+27i62m4bHARN7D/4cCu6ukOLlkmSRMMHx7hiTMcqiCepMOxCVkZgbY6MCjle8Pb5dOFNP7bREFoBZ+mogKbO80FurxvOoF+31vuMrVR37s1zuVh/AG7dbPM9VPjyJQhBweRz4vhLmVk2iKhZSYpxNgKlYDjaj/feJvByXQu0IjsPnApfnLptmaSUvjhFxvXLoDgEdZ8LfEG+1D+jnQtiDn9MX8pWmdMxLCalwrKJLKRo4/ycjNKQy0pKpOVlPAL/KphpewHsreJttwDK7ExGP6NsNK9d1zfdOujDkpzJHInjjv+hUJcAS/s0sLpetJoNQMayb9OHXxFungnAHnOD9UQqugvangaZ0Bvxbcso0WJi5gMlnHmM/ZZHw4JN+T5X/KDxGevj9YB0W+zKzRpFvEYFLRIeUnCHX4f8dlpPL
  template:
    metadata:
      name: doip-link-secret
      namespace: default
